name: CI

on:
  workflow_dispatch:
  release:
  push:
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        os: [windows-latest]
        node: [12]
        arch: [x86_64]
        include:
          - os: windows-latest
            arch: i686
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}}) Node.js ${{ matrix.node }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          # Set registry to NPM instead of github packages for publication
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ matrix.node }}

      - name: Setup Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y software-properties-common libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libxcb-xkb-dev libxkbfile-dev libxinerama-dev

      - name: Install Packages
        run: npm i --ignore-scripts

      - name: Build
        run: npm run build -- --all --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v') != true
        env:
          ARCH: ${{ matrix.arch }}

      - name: Build & Publish Prebuilds
        run: npm run build:ci -- --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tar package
        run: npm pack

      - name: Upload tar package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./*.tgz
