name: CI

on:
  workflow_dispatch:
  release:
  push:
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86_64]
        include:
          - os: windows-latest
            arch: i686
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          # Set registry to NPM instead of github packages for publication
          registry-url: 'https://registry.npmjs.org'
          node-version: 14

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Packages
        run: npm i --ignore-scripts

      # Build only if version tag is not present
      - name: Build
        run: npm run build -- --all
        if: startsWith(github.ref, 'refs/tags/v') != true
        env:
          ARCH: ${{ matrix.arch }}

      # Build and publish if version tag is present
      - name: Build & Publish Prebuilds
        run: npm run build:ci
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
